//Get User Info
export const FETCH_USER_INFO_BEGIN = 'FETCH_USER_INFO_BEGIN'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL'

//Get Banners
export const FETCH_BANNER_INFO_BEGIN = 'FETCH_BANNER_INFO_BEGIN'
export const FETCH_BANNER_INFO_SUCCESS = 'FETCH_BANNER_INFO_SUCCESS'
export const FETCH_BANNER_INFO_FAIL = 'FETCH_BANNER_INFO_FAIL'

//Get Blogs
export const FETCH_BLOG_INFO_BEGIN = 'FETCH_BLOG_INFO_BEGIN'
export const FETCH_BLOG_INFO_SUCCESS = 'FETCH_BLOG_INFO_SUCCESS'
export const FETCH_BLOG_INFO_FAIL = 'FETCH_BLOG_INFO_FAIL'

//Get Albums
export const FETCH_GALLERY_INFO_BEGIN = 'FETCH_GALLERY_INFO_BEGIN'
export const FETCH_GALLERY_INFO_SUCCESS = 'FETCH_GALLERY_INFO_SUCCESS'
export const FETCH_GALLERY_INFO_FAIL = 'FETCH_GALLERY_INFO_FAIL'

// Get Products
export const FETCH_PRODUCT_INFO_BEGIN = 'FETCH_PRODUCT_INFO_BEGIN'
export const FETCH_PRODUCT_INFO_SUCCESS = 'FETCH_PRODUCT_INFO_SUCCESS'
export const FETCH_PRODUCT_INFO_FAIL = 'FETCH_PRODUCT_INFO_FAIL'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

// Get Access Token
export const FETCH_ACCESS_TOKEN_BEGIN = 'FETCH_ACCESS_TOKEN_BEGIN'
export const FETCH_ACCESS_TOKEN_SUCCESS = 'FETCH_ACCESS_TOKEN_SUCCESS'
export const FETCH_ACCESS_TOKEN_FAIL = 'FETCH_ACCESS_TOKEN_FAIL'

// Get Order Status
export const FETCH_ORDER_STATUS_BEGIN = 'FETCH_ORDER_STATUS_BEGIN'
export const FETCH_ORDER_STATUS_SUCCESS = 'FETCH_ORDER_STATUS_SUCCESS'
export const FETCH_ORDER_STATUS_FAIL = 'FETCH_ORDER_STATUS_FAIL'

// Get User Name
export const FETCH_SUBDOMAIN_BEGIN = 'FETCH_SUBDOMAIN_BEGIN'
export const FETCH_SUBDOMAIN_SUCCESS = 'FETCH_SUBDOMAIN_SUCCESS'
export const FETCH_SUBDOMAIN_FAIL = 'FETCH_SUBDOMAIN_FAIL'

// FILTERS
export const FILTER_BRAND = 'FILTER_BRAND'
export const FILTER_COLOR = 'FILTER_COLOR'
export const FILTER_PRICE = 'FILTER_PRICE'
export const SORT_BY = 'SORT_BY'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'


// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_QTY = 'INCREMENT_QTY'
export const DECREMENT_QTY = 'DECREMENT_QTY'
export const RESET_CART = 'RESET_CART'



// WishList
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'


// Compare
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE'
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE'



// CheckOut Process
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

